spring:
  datasource:
    username: postgres
    password: admin1234
    url: jdbc:postgresql://music-post-it-db.cuyt0qdyrrfi.us-east-1.rds.amazonaws.com:5432/music_post_it
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8089