spring:
  datasource:
    username: postgres
    password: admin1234
    url: jdbc:postgres://music-post-it-db.cuyt0qdyrrfi.us-east-1.rds.amazonaws.com:5432
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
